### ISSUE TITLE
😁 I'm not entirely sure if it's possible to use mux.js to convert TS files to the MP4 format.

### ISSUE THREAD

**Issue by HereOrCode** [icefee/hls2mp4#1]
https://github.com/videojs/mux.js/ 

Lightweight utilities for inspecting and manipulating video container formats.

**Comment by icefee** [comment]
@code4you2021 Thanks for your propose, I tried do it before, but the Mp4 transmuxer of mux.js has no duration option provied. The related issue. [https://github.com/videojs/mux.js/issues/210](https://github.com/videojs/mux.js/issues/210) , that would cause the mp4 file generated has invalid metadata.

**Comment by HereOrCode** [comment]
Thank you for your response. Using your library has greatly increased the efficiency of my work.
