### ISSUE TITLE
Not working with No errors

### ISSUE THREAD

**Issue by AmanexDev** [icefee/hls2mp4#7]
is there a problem with my code? why this is not working when i try to call the handleDownload func nothing happens and no errors. showing 0 0 progress on console log

const hls2mp4 = new Hls2Mp4({ maxRetry: 3,tsDownloadConcurrency: 10, ffmpegBaseUrl:'https://unpkg.com/@ffmpeg/core@0.12.2/dist/umd/',
        onProgress: (type, progress) => {

        console.log(type, progress);
        },
        onError: (error) => {
            console.log(error)
        },
      });
    const handleDownload = async () => {
    const buffer = await hls2mp4.download('https://....m3u8');
    hls2mp4.saveToFile(buffer, "video.mp4");
    };

**Comment by icefee** [comment]
Thanks for your bug reporting!
Your code looks great. Can you provide a demo repository or your m3u8 url to reproduce the problem, like this.
[https://github.com/icefee/hls2mp4-demo](https://github.com/icefee/hls2mp4-demo)

**Comment by AmanexDev** [comment]
your repo works on my local. have you try this on react + vite? Im having issue on outputType but on your code i dont get this error. also i have the same version of ffmpeg and hls2mp4 you used. 
![Screenshot 2024-12-29 071137](https://github.com/user-attachments/assets/acdd4fe9-4623-4694-ab10-3197159fb428)
I tried to use your code snippet on my project.

**Comment by AmanexDev** [comment]
Yeah I figured out what's wrong with my code. this is working now thank you.
